channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - pytorch::pytorch=2.1.0
  - pytorch::pytorch-cuda=11.8
  - conda-forge::python=3.10
  - conda-forge::numpy=1.26.0
  - conda-forge::scipy=1.11.3
  - conda-forge::polars=0.19.12
  - conda-forge::matplotlib-base=3.8.1
  - conda-forge::h5py=3.10.0
  - conda-forge::hdf5plugin=4.2.0
  - conda-forge::tqdm=4.66.1
  - bioconda::pybigwig=0.3.22
  - bioconda::pyfaidx=0.7.2.1